### ISSUE TITLE
Question about pseudo modal

### ISSUE THREAD

**Issue by jimmy19991222** [MaHuanAAA/MoNIG#1]
Hi, Ma Huan. Thank you for your excellent open source code, but I have a small question.
In your paper, I found that you "directly concatenate _the features extracted from the temporal convolutional layers_ of different networks corresponding to different modalities as a pseudo modality", which indicates the pseudo modality is obtained by concatenate output of projection layer.
However, if CombModel is dealing with MoNIG-pseudo, I find the feature concatenated is _the output after another transformer encoder_. It is in ./src/models.py line 306. Is there any inconsistence between code and paper, or it is a misunderstanding?
Thank you.

**Comment by jimmy19991222** [comment]
Oh, there is actually an another question. If the hyp_params vonly, aonly, and lonly don't exist, some last_h wouldn't be defined in the backbone. Is this a remaining bug?

**Comment by MaHuanAAA** [comment]
Hi,

Here may be misunderstandings, the features are extracted from another encoder actually, and another encoder can help interactions between the modalities. I think what causes the misunderstanding could be the word "directly", which indicates that there is no additional operation on features extracted from the temporal convolutional layers.

**Comment by MaHuanAAA** [comment]
I can't understand what's your second question, can you explain the meaning of ``If the hyp_params vonly, aonly, and lonly don't exist,''?

**Comment by jimmy19991222** [comment]
It is in the backbone function,  last_h_l,  last_h_a and last_h_v are defined only when self.lonly, self.aonly, self.vonly is true...?

        if self.lonly:
            h_ls = self.trans_l_mem(proj_x_l)
            if type(h_ls) == tuple:
                h_ls = h_ls[0]
            last_h_l = last_hs = h_ls[-1]
        if self.aonly:
            h_as = self.trans_a_mem(proj_x_a)
            if type(h_as) == tuple:
                h_as = h_as[0]
            last_h_a = last_hs = h_as[-1]
        if self.vonly:
            h_vs = self.trans_v_mem(proj_x_v)
            if type(h_vs) == tuple:
                h_vs = h_vs[0]
            last_h_v = last_hs = h_vs[-1]

        return last_h_a, last_h_l, last_h_v

**Comment by jimmy19991222** [comment]
> Hi,
> 
> Here may be misunderstandings, the features are extracted from another encoder actually, and another encoder can help interactions between the modalities. I think what causes the misunderstanding could be the word "directly", which indicates that there is no additional operation on features extracted from the temporal convolutional layers.

Oh I see, thank you!

**Comment by MaHuanAAA** [comment]
> 

I don't remember whether it was default=True during the experiments, but I remember that we got embeddings with the correct dimensions here during the experiments.
