### ISSUE TITLE
AttributeError: module 'src.models' has no attribute 'MOE_PSEUDOModel'

### ISSUE THREAD

**Issue by SE-Nickjackson** [MaHuanAAA/MoNIG#2]
Sorry to bother you. Can you give me some advices to solve this problem? Detailed error information is as follows：
Traceback (most recent call last):
  File "F:/DAIP/multimodal/transfer_learning/MoNIG/main.py", line 169, in <module>
    acc7, acc2, f_score, mae, corr = train.initiate(hyp_params, train_loader, valid_loader, test_loader)
  File "F:\DAIP\multimodal\transfer_learning\MoNIG\src\train.py", line 11, in initiate
    model = getattr(models, hyp_params.model + 'Model')(hyp_params)
AttributeError: module 'src.models' has no attribute 'MOE_PSEUDOModel'

**Comment by MaHuanAAA** [comment]
Very sorry for that. Before releasing the code, we reorganized it to make it look more standardized, which may lead to changes in the naming of some functions since it was reorganized by different persons. This inconsistency has been modified. If you encounter other problems, you can point them out at any time. We are happy to provide any support, including the source of the processed dataset.

**Comment by SE-Nickjackson** [comment]
Thanks a lot. If you can provide the source of the processed dataset, I will appreciate it.

**Comment by MaHuanAAA** [comment]
I'm sorry that all the lab members came home for the Chinese New Year. The dataset was stored in Mobile Hard disk because it was too large, so we need to send someone back to the lab to get the dataset, which may take several days.

**Comment by MaHuanAAA** [comment]
We found that all datasets are publicly available, and their links are:

Superconductivty: https://archive.ics.uci.edu/ml/datasets/Superconductivty+Data
CT Slices: https://archive.ics.uci.edu/ml/datasets/Relative+location+of+CT+slices+on+axial+axis
MOSEI&MOSI: https://github.com/A2Zadeh/CMU-MultimodalSDK

Good luck!

**Comment by MaHuanAAA** [comment]
link：https://pan.baidu.com/s/1xgt3o3HHPlWyx501pQ071A 
code：8s73 
The original link seems closed, this may help you, .pt contains torch tensors of original data.
