### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by feifeiflysky** [MaHuanAAA/MoNIG#3]
Sorry to bother you, can you explain what do the 'self.text.shape[0] self.text.shape[1]self.text.shape[2]' represent ?  I do not konw how to orgnize the data with the right form, can you provide me an example of the dataset?

**Comment by MaHuanAAA** [comment]
link：https://pan.baidu.com/s/1xgt3o3HHPlWyx501pQ071A 
code：8s73 

Here is the data, .pkl and .pt indicate original data and torch tensors respectively.

**Comment by feifeiflysky** [comment]
Thanks for your reply and the code runs very well .There is another question,  there are only 750 samples in my dataset  and it performs not so well , do you have some ways  to deal with this problem?

**Comment by MaHuanAAA** [comment]
Maybe you should finetune a pre-trained model instead of training a new model on your dataset.
